### PR TITLE
Check Ai version for proper functionality

### LINKED ISSUE #6: selectTool
The `app.selectTool()` method was added in Adobe Illustrator v24 (CC 2020). But users of earlier versions (CC 2019, 2018, etc) don't know such details and will get an error like this: `Adobe Area Type Tool. ReferenceError: app.selectTool is not a function`.

I had an idea that could check the version of Adobe Illustrator in the script:
```
var aiVers = parseInt(app.version);
if (aiVers < 24) ... 
```
And then don't show `showBuiltInTools()` in Settings and search field. If the user has more than one version of Adobe Illustrator installed: created a custom workflow in Ai CC 2022 with a built-in tool call, and then ran the script in Ai CC 2019, then yes will get a ReferenceError. You can add to the error text a hint that `Adobe Illustrator <put version> doesn't support built-in tools`. Then the .csv of the localizations will also be updated.

It gives more clarity to the user. What do you think?

### PR DESCRIPTION
**Pull request by joshbduncan**
Hey, I think I've got a decent idea of how to disable commands that don't meet a minimum version.

I added a new const called `versionedCommands` which is an object containing commands or entire subsets of commands that need to be versioned checked for presenting them in the palette.

Then, I iterate through the `versionedCommands` to check to see if their minVersion is greater than the current Ai version. If so, the command or set of commands will be deleted. I think this is better than a bunch of if statements for each version.

I set the minVersion high on each of the three currently listed so you can test it out. Works great on my end as all of the tools are hidden, the "Show All Tools..." command is hidden, and the "Window > History" command is hidden. Not sure how far I'd want to go back since there is no good documentation on what was added or removed when.

I was a bit concerned this might slow the opening of the palette but it doesn't seem to have much of an effect. If the list of versioned command got super long it may start to slow things down.

When you get a chance, please download the English version and check it out and let me know what you think. PLEASE NOTE, that I didn't include any localized version in the commit. I will include those once we get something we can agree is a good solution.

Thanks aging for your help!

#6

### CODE REVIEW

**Comment by creold** [comment]
I checked on Mac OS Adobe Illustrator v26.4, v23.1. It runs fast. I changed the `minVersion` and it works!

I made a test workflow containing one built-in tool command and "Window > History" command. In early Illustrator, the amount of alert windows equaled the amount of unsupported commands. And it can get tiring clicking "OK" on every alert window. What if the workfow contains three, five unsupported commands and the user will see a cascade of alerts :-)

Using `versionedCommands` maybe skip all unsupported steps when starting a user's workflow? To make the user understand, at the end of the workflow you can show the only message "Skipped unsupported commands: N". But of course we need to check whether analyzing all workflow steps by `minVersion` will reduce the speed of starting workflow.

**Comment by joshbduncan** [comment]
Ah, yes, what you earlier about "someone having multiple versions of Ai installed" makes more sense now. I can insert a check where before a workflow is run all of its steps are checked for version compatibility. Nice catch!

**Comment by joshbduncan** [comment]
@creold, check out this latest commit. I added a check right after the deleted command check. It iterates through all the workflow commands and checks to see if any are incompatible. If so, it presents a dialog explaining such and even lists the offending actions. Works well on my end so check it out and let me know what you think?.

PLEASE NOTE: This commit contains some other updates I merged in from main. Also, the German and Russian versions are not correct.

**Comment by creold** [comment]
@joshbduncan, I understand correctly that now any commands are marked incompatible in the `if (!allCommands.hasOwnProperty(actions[i]))` to test the functionality? Because the "RGB Color" command also indicated incompatible.
incompatible

**Comment by joshbduncan** [comment]
That's odd. I'll dig in and see what's wrong in a little bit and let you know.

**Comment by joshbduncan** [comment]
@creold, so I rewrote the compatibility checker actually combined it with the deleted commands checker.

You'll find a new function `checkWorkflow()` that iterates through every action in a workflow and tracks any that are deleted or incompatible. If it finds deleted action it will present a dialog and explain. If it finds incompatible actions it will also present a dialog and explain. So you could actually get two dialogs if your workflow contained both deleted and incompatible actions (should be a rare occasion). I originally combined both alerts into one but I found it hard to explain which were deleted and which were incompatible.

As for why it was accidentally marking File > Document Color Mode > RGB Color. I was using the wrong method to check if the command was available. That should be fixed now too.

Have a look and let me know what you think? Thanks!

**Comment by creold** [comment]
That's great progress. I checked alert with deleted commands and incompatible commands by changing `minVersion`. I think it's time to add new messages to the CSV template and Kurt and I should translate them into two languages :-)

**Comment by joshbduncan** [comment]
@creold, so I had a better idea to handle all of this. When the script is first run, I already go through every possible command via the "data" object so that I can build the "allCommands" object for the particular instance. It would be easier to check for the minimum version while doing the build. This would also make maintaining this functionality easier since the minVersion is stored with the original command.

This would work for any type of command (defaults, menu, or tool).

The build  process works like this (while iterating through all of the possible commands):
Step 1. Does this command have the property minVersion?
  IF YES: Is minVersion > the current Ai version?
    IF YES: Don't add this command to "allCommands" and delete it from "data" so it doesn't show in menus.
  ELSE: add the command to "allCommands"

This way, I only have to add the minVersion property to any commands that require it.

To make testing a bit easier. I added a line at the top where you can just set the Ai version to 0 or whatever to make the compatibility check fail.

Give it a try and let me know what you think. If it works for you, I can update the translation CSVs and let Kurt know.

Thanks!

**Comment by creold** [comment]
@joshbduncan , that's an interesting solution. The performance is at the same level. Tested in two versions of Illustrator. In future, of course, there is a chance that Adobe will add some more commands that will not be supported in earlier AI versions and it will be possible to specify each individual `minVersion`.

**Comment by joshbduncan** [comment]
@creold, yeah, I went with this solution to make future updates easier.

If a new tool or menu command is added then it's as simple as adding it at the bottom and putting a minVersion on it.

And, I was waiting for your comments so if you like this solution I will also add a maxVersion setting now too so that in the future if a tool or menu command is removed it doesn't have to be removed from the script just tagged with a maxVersion.

Since there are so many tools and menu commands (over 600 combined) I want to make maintaining them a easy as possible.

**Comment by creold** [comment]
I hadn't thought of that. Indeed, because Adobe team likes to quietly remove support for some commands and `executeMenuCommand()` has no current documentation. Your script can become such a "documentation" for other developers, as it will contain the minimum and maximum version keys for each command.

P.S. We have different time zones. It's morning for me and I'm awake :-)

**Comment by joshbduncan** [comment]
@creold, could you translate the two string below for me please. Those are all that changed in this version. Thanks!

Workflow needs attention.\nThe following action steps from your workflow are are no longer available.\n\n

Workflow needs attention.\nThe following action steps from your workflow are incompatible with your version of Illustrator.\n\n

**Comment by creold** [comment]
**New**
Workflow needs attention.\nThe following action steps from your workflow are are no longer available.\n\n
`Внимание\nУказанные шаги в вашем наборе команд больше недоступны\n\n`

Workflow needs attention.\nThe following action steps from your workflow are incompatible with your version of Illustrator.\n\n
`Внимание\nУказанные шаги в вашем наборе команд несовместимы с этой версией Illustrator\n\n`

**Corrected my EN-RU mistakes:**

File > Save as Template...
`Файл > Сохранить как шаблон...`

File > Save Selected Slices...
`Файл > Сохранить выделенные фрагменты...`

Edit > Color Settings...
`Редактирование > Настройка цветов...`

**Comment by joshbduncan** [comment]
@creold, I have your edits made to the translation file. Once I hear back from Kurt, I'll get this merged in and start working on the screen flashing bug on windows. Thanks again!

**Comment by joshbduncan** [comment]
@creold, I added in the maxVersion check and cleaned things up a bit. So now, if say Ai gets rid of the "Direct Selection Tool" in v26.5 I'll just have to add `maxVersion: 26.4` to the tool, and anyone with a version higher than that would not have access to it. Work just like the minVersion. Try it out and let me know what you think. I've got the updated translations added from you and Kurt, so if everything works for you I'll get this merged into main. Thanks!

**Comment by creold** [comment]
@joshbduncan I checked the `maxVersion` key on random tools. It works in different localizations. Also checked the new message texts in the Russian version.

**Pull request merged**
